#ifndef UE4SS_SDK_SettingsUI_New_HPP
#define UE4SS_SDK_SettingsUI_New_HPP

class USettingsUI_New_C : public UUserWidget
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetAnimation* FadeDialog;
    class UButton* BackToMenuButton;
    class UButton* Button_DeleteAllCrystals;
    class UButton* Button_GenerateRecipe;
    class UButton* Button_KillMe;
    class UButton* Button_KillMeHalf;
    class UGraphicsSettingCategoryButton_C* CategoryAestheticsButton;
    class UGraphicsSettingCategoryButton_C* CategoryGameplayButton;
    class UGraphicsSettingCategoryButton_C* CategoryPerformanceButton;
    class UGraphicsSettingCategoryButton_C* CategoryStatsButton;
    class UTextBlock* ChunkFormatText;
    class UTextBlock* ChunkFormatTextLeft;
    class UTextBlock* ChunkNumberText;
    class UTextBlock* ChunkNumberTextLeft;
    class UGraphicsSetting_New_C* GraphicsSetting;
    class UGraphicsSetting_New_C* GraphicsSetting_C_2;
    class UGraphicsSetting_New_C* GraphicsSetting_C_3;
    class UGraphicsSetting_New_C* GraphicsSetting_C_4;
    class UGraphicsSetting_New_C* GraphicsSetting_C_5;
    class UGraphicsSetting_New_C* GraphicsSetting_C_6;
    class UGraphicsSetting_New_C* GraphicsSetting_C_7;
    class UGraphicsSetting_New_C* GraphicsSetting_C_8;
    class UGraphicsSetting_New_C* GraphicsSetting_C_9;
    class UGraphicsSetting_New_C* GraphicsSetting_C_10;
    class UGraphicsSetting_New_C* GraphicsSetting_C_12;
    class UGraphicsSetting_New_C* GraphicsSetting_C_13;
    class UGraphicsSetting_New_C* GraphicsSetting_C_15;
    class UGraphicsSetting_New_C* GraphicsSetting_C_16;
    class UGraphicsSetting_New_C* GraphicsSetting_C_17;
    class UGraphicsSetting_New_C* GraphicsSetting_C_DistantTreeShadows;
    class UGraphicsSetting_New_C* GraphicsSetting_C_Screenshot;
    class UGraphicsSetting_New_C* GraphicsSetting_ColorScheme;
    class UGraphicsSetting_New_C* GraphicsSetting_ControlScheme;
    class UGraphicsSetting_New_C* GraphicsSetting_Death;
    class UGraphicsSetting_New_C* GraphicsSetting_DLSS;
    class UGraphicsSetting_New_C* GraphicsSetting_Flicker;
    class UGraphicsSetting_New_C* GraphicsSetting_FocusWarning;
    class UGraphicsSetting_New_C* GraphicsSetting_FoveatedTAA;
    class UGraphicsSetting_New_C* GraphicsSetting_ImageBrightness;
    class UGraphicsSetting_New_C* GraphicsSetting_LightshaftIntensity;
    class UGraphicsSetting_New_C* GraphicsSetting_MovementOrientation;
    class UGraphicsSetting_New_C* GraphicsSetting_NightDarkness;
    class UGraphicsSetting_New_C* GraphicsSetting_RTXShadow;
    class UGraphicsSetting_New_C* GraphicsSetting_ShadowQuality;
    class UGraphicsSetting_New_C* GraphicsSetting_ShowAdvancedSettings;
    class UGraphicsSetting_New_C* GraphicsSetting_SmallShadow;
    class UGraphicsSetting_New_C* GraphicsSetting_TeleportLocationFade;
    class UGraphicsSetting_New_C* GraphicsSetting_TerrainLOD;
    class UGraphicsSetting_New_C* GraphicsSetting_ToolHitItemSmoke;
    class UGraphicsSetting_New_C* GraphicsSetting_TreeDistanceQuality;
    class UGraphicsSetting_New_C* GraphicsSetting_TurningMode;
    class UGraphicsSetting_New_C* GraphicsSetting_ViewDistance;
    class UHorizontalBox* HorizontalBox_DeleteCrystals;
    class UHorizontalBox* HorizontalBox_SettingHelp;
    class UImage* Image;
    class UImage* Image_0;
    class UImage* Image_1;
    class UImage* Image_2;
    class UImage* Image_3;
    class UImage* Image_31;
    class UMultiLineEditableTextBox* MultiLineEditableTextBox_0;
    class UButton* NotReallyLeave;
    class UTextBlock* PlayerLocationText;
    class UBorder* ReallyLeaveOverlay;
    class URetainerBox* RetainerBox_0;
    class UTextBlock* SettingHelpText;
    class USettingsSlider_C* SettingsSlider_AAStrength;
    class USettingsSlider_C* SettingsSlider_C_0;
    class USettingsSlider_C* SettingsSlider_C_1;
    class USettingsSlider_C* SettingsSlider_C_2;
    class USettingsSlider_C* SettingsSlider_C_3;
    class USettingsSlider_C* SettingsSlider_C_BucketAngle1;
    class USettingsSlider_C* SettingsSlider_C_BucketAngle2;
    class USettingsSlider_C* SettingsSlider_Music;
    class USettingsSlider_C* SettingsSlider_Resolution;
    class USettingsSlider_C* SettingsSlider_Sharpen;
    class USettingsSlider_C* SettingsSlider_TurningSpeed;
    class USettingsSlider_C* SettingsSlider_WalkingSpeed;
    class UTextBlock* TextBlock_5;
    class UTextBlock* TextBlock_6;
    class UTextBlock* TextBlock_7;
    class UTextBlock* TextBlock_8;
    class UTextBlock* TextBlock_9;
    class UTextBlock* TextBlock_10;
    class UTextBlock* TextBlock_11;
    class UTextBlock* TextBlock_12;
    class UTextBlock* TextBlock_TotalMinedBlocks;
    class UTextBlock* TotalCraftedBlocks;
    class UTextBlock* TotalMinedBlocks;
    class UTextBlock* TotalMinedBlocks_10Min;
    class UTextBlock* TotalMinedBlocks_10MinCurrentUserRank;
    class UTextBlock* TotalMinedBlocks_10MinLocalBest;
    class UTextBlock* TotalMinedBlocks_10MinWorldBest;
    class UTextBlock* TotalMinedBlocks_10MinWorldBest_RecordHolder;
    class UTextBlock* TotalPlacedBlocks;
    class UWidgetSwitcher* WidgetSwitcher_171;
    class UButton* YesReallyLeave;
    TMap<class FString, class UGraphicsSetting_New_C*> SettingWidgetsMap;
    TArray<class UGraphicsSetting_New_C*> SettingWidgetsArray;
    class UMaterialInstanceDynamic* RetainerMat;
    float CurrentBlur;
    float BlurTarget;
    bool ExpertEnabled;

    void SetExpertSettingsEnabledDelay();
    void Set Expert Settings Enabled(bool Enabled);
    void Completed_DA3564B34411921ECAF259861CC80A31(bool bSuccessful, FUWorksSteamLeaderboard SteamLeaderboard, bool bLeaderboardFound);
    void Completed_33C9116F4501F4D3D762C8B07D7CF222(bool bSuccessful, FUWorksSteamLeaderboard SteamLeaderboard, FUWorksSteamLeaderboardEntries SteamLeaderboardEntries, int32 EntryCount);
    void BndEvt__Button_1_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature();
    void BndEvt__YesReallyLeave_K2Node_ComponentBoundEvent_281_OnButtonReleasedEvent__DelegateSignature();
    void Construct();
    void InitRetainer();
    void SetRetainerBlur(bool Enabled);
    void Tick(FGeometry MyGeometry, float InDeltaTime);
    void BndEvt__NotReallyLeave_K2Node_ComponentBoundEvent_64_OnButtonPressedEvent__DelegateSignature();
    void UpdateChunkFormatText();
    void BndEvt__Button_GenerateRecipe_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature();
    void UpdatePlayerLocationText(class AChunkManagerBP_C* ChunkManager);
    void BndEvt__GraphicsSettingCategoryButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature();
    void BndEvt__CategoryAestheticsButton_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature();
    void BndEvt__CategoryGameplayButton_K2Node_ComponentBoundEvent_4_Clicked__DelegateSignature();
    void BndEvt__CategoryStatsButton_K2Node_ComponentBoundEvent_5_Clicked__DelegateSignature();
    void DisselectCategoryButtons();
    void FindWorldBest();
    void ShowSettingHelpText(FString Text);
    void HideSettingHelpText();
    void PreConstruct(bool IsDesignTime);
    void BndEvt__SettingsUI_New_Button_KillMe_K2Node_ComponentBoundEvent_6_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__SettingsUI_New_Button_KillMeHalf_K2Node_ComponentBoundEvent_8_OnButtonPressedEvent__DelegateSignature();
    void BndEvt__SettingsUI_New_Button_DeleteAllCrystals_K2Node_ComponentBoundEvent_7_OnButtonPressedEvent__DelegateSignature();
    void ExecuteUbergraph_SettingsUI_New(int32 EntryPoint);
};

#endif
