#ifndef UE4SS_SDK_Mod_PCMovement_HPP
#define UE4SS_SDK_Mod_PCMovement_HPP

class AMod_PCMovement_C : public AActor
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UWidgetInteractionComponent* WidgetInteraction;
    class USceneComponent* DefaultSceneRoot;
    FVector Location;
    FRotator Rotation;
    float MovementSpeed;
    float RotationDegree;
    class UHUD_C* HUDRef;
    float TempSmallDistance;
    bool ForwardPressed;
    bool BackwardPressed;
    bool LeftPressed;
    bool RightPressed;
    bool LookRightPressed;
    bool LookLeftPressed;
    bool PitchUpPressed;
    bool PitchDownPressed;
    bool UpPressed;
    bool DownPressed;
    bool RollLeftPressed;
    bool RollRightPressed;
    bool IncreaseMovementSpeedPressed;
    bool DecreaseMovementSpeedPressed;
    bool IncreaseRotationSpeedPressed;
    bool DecreaseRotationSpeedPressed;
    float RotationChangeRate;
    float MovementChangeRate;
    FVector OriginalLocation;
    FText KeybindsText;
    bool IsKeybindsOpen;
    FIntVector AbsoluteLocation;
    class UFreecam_SaveData_C* FreecamSaveData;
    FString SavePath;
    bool IsCoordsOpen;
    bool IsTimeLocked;
    bool IsHeadLampEnabled;
    class USpotLightComponent* HeadLampRef;
    class UPointLightComponent* PointLightRef;
    bool IncreaseDilationPressed;
    bool DecreaseDilationPressed;
    float TimeDilation;

    void SetTimeDilation();
    void NewRandomWeather();
    void ResetWeatherToRegular();
    void CreateHeadLamp();
    void ToggleHeadLamp();
    void SetTime(float Time);
    void ToggleTimeLock();
    void LockTime();
    void ToggleMusic();
    void ShowCoords();
    void HideCoords();
    void SetKeybindsText();
    void DisablePlayerGravity();
    void SetStartLocation();
    void SetOriginalLocations();
    void MovePlayer();
    void Move Player Components();
    void RemoveHands();
    void SetHUDWidgetData();
    void GetWorldName(FString& World Name);
    void GoToSpawn();
    void ToggleKeybinds();
    void ToggleCoords();
    void GoHome();
    void SetHome();
    void TeleportAnimals();
    void KillAnimals();
    void SaveSaveData();
    void LoadDataFromSave();
    void LoadSave();
    void InpActEvt_W_K2Node_InputKeyEvent_55(FKey Key);
    void InpActEvt_W_K2Node_InputKeyEvent_54(FKey Key);
    void InpActEvt_S_K2Node_InputKeyEvent_53(FKey Key);
    void InpActEvt_S_K2Node_InputKeyEvent_52(FKey Key);
    void InpActEvt_D_K2Node_InputKeyEvent_51(FKey Key);
    void InpActEvt_D_K2Node_InputKeyEvent_50(FKey Key);
    void InpActEvt_A_K2Node_InputKeyEvent_49(FKey Key);
    void InpActEvt_A_K2Node_InputKeyEvent_48(FKey Key);
    void InpActEvt_SpaceBar_K2Node_InputKeyEvent_47(FKey Key);
    void InpActEvt_SpaceBar_K2Node_InputKeyEvent_46(FKey Key);
    void InpActEvt_RightShift_K2Node_InputKeyEvent_45(FKey Key);
    void InpActEvt_RightShift_K2Node_InputKeyEvent_44(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_43(FKey Key);
    void InpActEvt_LeftShift_K2Node_InputKeyEvent_42(FKey Key);
    void InpActEvt_Left_K2Node_InputKeyEvent_41(FKey Key);
    void InpActEvt_Left_K2Node_InputKeyEvent_40(FKey Key);
    void InpActEvt_Right_K2Node_InputKeyEvent_39(FKey Key);
    void InpActEvt_Right_K2Node_InputKeyEvent_38(FKey Key);
    void InpActEvt_Up_K2Node_InputKeyEvent_37(FKey Key);
    void InpActEvt_Up_K2Node_InputKeyEvent_36(FKey Key);
    void InpActEvt_Down_K2Node_InputKeyEvent_35(FKey Key);
    void InpActEvt_Down_K2Node_InputKeyEvent_34(FKey Key);
    void InpActEvt_F1_K2Node_InputKeyEvent_33(FKey Key);
    void InpActEvt_Q_K2Node_InputKeyEvent_32(FKey Key);
    void InpActEvt_Q_K2Node_InputKeyEvent_31(FKey Key);
    void InpActEvt_E_K2Node_InputKeyEvent_30(FKey Key);
    void InpActEvt_E_K2Node_InputKeyEvent_29(FKey Key);
    void InpActEvt_Divide_K2Node_InputKeyEvent_28(FKey Key);
    void InpActEvt_Divide_K2Node_InputKeyEvent_27(FKey Key);
    void InpActEvt_Multiply_K2Node_InputKeyEvent_26(FKey Key);
    void InpActEvt_Multiply_K2Node_InputKeyEvent_25(FKey Key);
    void InpActEvt_NumPadEight_K2Node_InputKeyEvent_24(FKey Key);
    void InpActEvt_NumPadEight_K2Node_InputKeyEvent_23(FKey Key);
    void InpActEvt_NumPadNine_K2Node_InputKeyEvent_22(FKey Key);
    void InpActEvt_NumPadNine_K2Node_InputKeyEvent_21(FKey Key);
    void InpActEvt_NumPadZero_K2Node_InputKeyEvent_20(FKey Key);
    void InpActEvt_#_K2Node_InputKeyEvent_19(FKey Key);
    void InpActEvt_Enter_K2Node_InputKeyEvent_18(FKey Key);
    void InpActEvt_Enter_K2Node_InputKeyEvent_17(FKey Key);
    void InpActEvt_Home_K2Node_InputKeyEvent_16(FKey Key);
    void InpActEvt_F2_K2Node_InputKeyEvent_15(FKey Key);
    void InpActEvt_F3_K2Node_InputKeyEvent_14(FKey Key);
    void InpActEvt_F4_K2Node_InputKeyEvent_13(FKey Key);
    void InpActEvt_RightBracket_K2Node_InputKeyEvent_12(FKey Key);
    void InpActEvt_LeftBracket_K2Node_InputKeyEvent_11(FKey Key);
    void InpActEvt_P_K2Node_InputKeyEvent_10(FKey Key);
    void InpActEvt_H_K2Node_InputKeyEvent_9(FKey Key);
    void InpActEvt_R_K2Node_InputKeyEvent_8(FKey Key);
    void InpActEvt_T_K2Node_InputKeyEvent_7(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_6(FKey Key);
    void InpActEvt_PageUp_K2Node_InputKeyEvent_5(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_4(FKey Key);
    void InpActEvt_PageDown_K2Node_InputKeyEvent_3(FKey Key);
    void InpActEvt_M_K2Node_InputKeyEvent_2(FKey Key);
    void InpActEvt_K_K2Node_InputKeyEvent_1(FKey Key);
    void InpActEvt_L_K2Node_InputKeyEvent_0(FKey Key);
    void ReceiveBeginPlay();
    void ReceiveTick(float DeltaSeconds);
    void ExecuteUbergraph_Mod_PCMovement(int32 EntryPoint);
};

#endif
