enum class EUWorksResult {
    Unknown = 0,
    OK = 1,
    Fail = 2,
    NoConnection = 3,
    InvalidPassword = 5,
    LoggedInElsewhere = 6,
    InvalidProtocolVer = 7,
    InvalidParam = 8,
    FileNotFound = 9,
    Busy = 10,
    InvalidState = 11,
    InvalidName = 12,
    InvalidEmail = 13,
    DuplicateName = 14,
    AccessDenied = 15,
    Timeout = 16,
    Banned = 17,
    AccountNotFound = 18,
    InvalidSteamID = 19,
    ServiceUnavailable = 20,
    NotLoggedOn = 21,
    Pending = 22,
    EncryptionFailure = 23,
    InsufficientPrivilege = 24,
    LimitExceeded = 25,
    Revoked = 26,
    Expired = 27,
    AlreadyRedeemed = 28,
    DuplicateRequest = 29,
    AlreadyOwned = 30,
    IPNotFound = 31,
    PersistFailed = 32,
    LockingFailed = 33,
    LogonSessionReplaced = 34,
    ConnectFailed = 35,
    HandshakeFailed = 36,
    IOFailure = 37,
    RemoteDisconnect = 38,
    ShoppingCartNotFound = 39,
    Blocked = 40,
    Ignored = 41,
    NoMatch = 42,
    AccountDisabled = 43,
    ServiceReadOnly = 44,
    AccountNotFeatured = 45,
    AdministratorOK = 46,
    ContentVersion = 47,
    TryAnotherCM = 48,
    PasswordRequiredToKickSession = 49,
    AlreadyLoggedInElsewhere = 50,
    Suspended = 51,
    Cancelled = 52,
    DataCorruption = 53,
    DiskFull = 54,
    RemoteCallFailed = 55,
    PasswordUnset = 56,
    ExternalAccountUnlinked = 57,
    PSNTicketInvalid = 58,
    ExternalAccountAlreadyLinked = 59,
    RemoteFileConflict = 60,
    IllegalPassword = 61,
    SameAsPreviousValue = 62,
    AccountLogonDenied = 63,
    CannotUseOldPassword = 64,
    InvalidLoginAuthCode = 65,
    AccountLogonDeniedNoMail = 66,
    HardwareNotCapableOfIPT = 67,
    IPTInitError = 68,
    ParentalControlRestricted = 69,
    FacebookQueryError = 70,
    ExpiredLoginAuthCode = 71,
    IPLoginRestrictionFailed = 72,
    AccountLockedDown = 73,
    AccountLogonDeniedVerifiedEmailRequired = 74,
    NoMatchingURL = 75,
    BadResponse = 76,
    RequirePasswordReEntry = 77,
    ValueOutOfRange = 78,
    UnexpectedError = 79,
    Disabled = 80,
    InvalidCEGSubmission = 81,
    RestrictedDevice = 82,
    RegionLocked = 83,
    RateLimitExceeded = 84,
    AccountLoginDeniedNeedTwoFactor = 85,
    ItemDeleted = 86,
    AccountLoginDeniedThrottle = 87,
    TwoFactorCodeMismatch = 88,
    TwoFactorActivationCodeMismatch = 89,
    AccountAssociatedToMultiplePartners = 90,
    NotModified = 91,
    NoMobileDevice = 92,
    TimeNotSynced = 93,
    SmsCodeFailed = 94,
    AccountLimitExceeded = 95,
    AccountActivityLimitExceeded = 96,
    PhoneActivityLimitExceeded = 97,
    RefundToWallet = 98,
    EmailSendFailure = 99,
    NotSettled = 100,
    NeedCaptcha = 101,
    GSLTDenied = 102,
    GSOwnerDenied = 103,
    InvalidItemType = 104,
    IPBanned = 105,
    GSLTExpired = 106,
    EUWorksResult_MAX = 107,
};

enum class EUWorksChatRoomEnterResponse {
    Unknown = 0,
    Success = 1,
    DoesntExist = 2,
    NotAllowed = 3,
    Full = 4,
    Error = 5,
    Banned = 6,
    Limited = 7,
    ClanDisabled = 8,
    CommunityBan = 9,
    MemberBlockedYou = 10,
    YouBlockedMember = 11,
    EUWorksChatRoomEnterResponse_MAX = 12,
};

enum class EUWorksPersonaChange {
    Name = 0,
    Status = 1,
    ComeOnline = 2,
    GoneOffline = 3,
    GamePlayed = 4,
    GameServer = 5,
    Avatar = 6,
    JoinedSource = 7,
    LeftSource = 8,
    RelationshipChanged = 9,
    NameFirstSet = 10,
    FacebookInfo = 11,
    Nickname = 12,
    SteamLevel = 13,
    EUWorksPersonaChange_MAX = 14,
};

enum class EUWorksAuthSessionResponse {
    OK = 0,
    UserNotConnectedToSteam = 1,
    NoLicenseOrExpired = 2,
    VACBanned = 3,
    LoggedInElseWhere = 4,
    VACCheckTimedOut = 5,
    AuthTicketCanceled = 6,
    AuthTicketInvalidAlreadyUsed = 7,
    AuthTicketInvalid = 8,
    PublisherIssuedBan = 9,
    EUWorksAuthSessionResponse_MAX = 10,
};

enum class EUWorksFavoriteFlags {
    Unknown = 0,
    Favorite = 1,
    History = 2,
    EUWorksFavoriteFlags_MAX = 3,
};

enum class EUWorksChatMemberStateChange {
    Entered = 0,
    Left = 1,
    Disconnected = 2,
    Kicked = 3,
    Banned = 4,
    EUWorksChatMemberStateChange_MAX = 5,
};

enum class EUWorksChatEntryType {
    Invalid = 0,
    ChatMessage = 1,
    Typing = 2,
    InviteGame = 3,
    Emote = 4,
    LeftConversation = 6,
    Entered = 7,
    WasKicked = 8,
    WasBanned = 9,
    Disconnected = 10,
    HistoricalChat = 11,
    LinkBlocked = 14,
    EUWorksChatEntryType_MAX = 15,
};

enum class EUWorksP2PSessionError {
    None = 0,
    NotRunningApp = 1,
    NoRightsToApp = 2,
    DestinationNotLoggedIn = 3,
    Timeout = 4,
    Max = 5,
};

enum class EUWorksDenyReason {
    Invalid = 0,
    InvalidVersion = 1,
    Generic = 2,
    NotLoggedOn = 3,
    NoLicense = 4,
    Cheater = 5,
    LoggedInElseWhere = 6,
    UnknownText = 7,
    IncompatibleAnticheat = 8,
    MemoryCorruption = 9,
    IncompatibleSoftware = 10,
    SteamConnectionLost = 11,
    SteamConnectionError = 12,
    SteamResponseTimedOut = 13,
    SteamValidationStalled = 14,
    SteamOwnerLeftGuestUser = 15,
    EUWorksDenyReason_MAX = 16,
};

enum class EUWorksFailureType {
    FlushedCallbackQueue = 0,
    PipeFail = 1,
    EUWorksFailureType_MAX = 2,
};

enum class EUWorksSteamControllerPad {
    Left = 0,
    Right = 1,
    EUWorksSteamControllerPad_MAX = 2,
};

enum class EUWorksSteamControllerLEDFlag {
    SetColor = 0,
    RestoreUserDefault = 1,
    EUWorksSteamControllerLEDFlag_MAX = 2,
};

enum class EUWorksControllerSourceMode {
    None = 0,
    Dpad = 1,
    Buttons = 2,
    FourButtons = 3,
    AbsoluteMouse = 4,
    RelativeMouse = 5,
    JoystickMove = 6,
    JoystickMouse = 7,
    JoystickCamera = 8,
    ScrollWheel = 9,
    Trigger = 10,
    TouchMenu = 11,
    MouseJoystick = 12,
    MouseRegion = 13,
    RadialMenu = 14,
    Switches = 15,
    EUWorksControllerSourceMode_MAX = 16,
};

enum class EUWorksControllerSource {
    None = 0,
    LeftTrackpad = 1,
    RightTrackpad = 2,
    Joystick = 3,
    ABXY = 4,
    Switch = 5,
    LeftTrigger = 6,
    RightTrigger = 7,
    Gyro = 8,
    CenterTrackpad = 9,
    RightJoystick = 10,
    DPad = 11,
    Count = 12,
    EUWorksControllerSource_MAX = 13,
};

enum class EUWorksControllerActionOrigin {
    None = 0,
    A = 1,
    B = 2,
    X = 3,
    Y = 4,
    LeftBumper = 5,
    RightBumper = 6,
    LeftGrip = 7,
    RightGrip = 8,
    Start = 9,
    Back = 10,
    LeftPad_Touch = 11,
    LeftPad_Swipe = 12,
    LeftPad_Click = 13,
    LeftPad_DPadNorth = 14,
    LeftPad_DPadSouth = 15,
    LeftPad_DPadWest = 16,
    LeftPad_DPadEast = 17,
    RightPad_Touch = 18,
    RightPad_Swipe = 19,
    RightPad_Click = 20,
    RightPad_DPadNorth = 21,
    RightPad_DPadSouth = 22,
    RightPad_DPadWest = 23,
    RightPad_DPadEast = 24,
    LeftTrigger_Pull = 25,
    LeftTrigger_Click = 26,
    RightTrigger_Pull = 27,
    RightTrigger_Click = 28,
    LeftStick_Move = 29,
    LeftStick_Click = 30,
    LeftStick_DPadNorth = 31,
    LeftStick_DPadSouth = 32,
    LeftStick_DPadWest = 33,
    LeftStick_DPadEast = 34,
    Gyro_Move = 35,
    Gyro_Pitch = 36,
    Gyro_Yaw = 37,
    Gyro_Roll = 38,
    PS4_X = 39,
    PS4_Circle = 40,
    PS4_Triangle = 41,
    PS4_Square = 42,
    PS4_LeftBumper = 43,
    PS4_RightBumper = 44,
    PS4_Options = 45,
    PS4_Share = 46,
    PS4_LeftPad_Touch = 47,
    PS4_LeftPad_Swipe = 48,
    PS4_LeftPad_Click = 49,
    PS4_LeftPad_DPadNorth = 50,
    PS4_LeftPad_DPadSouth = 51,
    PS4_LeftPad_DPadWest = 52,
    PS4_LeftPad_DPadEast = 53,
    PS4_RightPad_Touch = 54,
    PS4_RightPad_Swipe = 55,
    PS4_RightPad_Click = 56,
    PS4_RightPad_DPadNorth = 57,
    PS4_RightPad_DPadSouth = 58,
    PS4_RightPad_DPadWest = 59,
    PS4_RightPad_DPadEast = 60,
    PS4_CenterPad_Touch = 61,
    PS4_CenterPad_Swipe = 62,
    PS4_CenterPad_Click = 63,
    PS4_CenterPad_DPadNorth = 64,
    PS4_CenterPad_DPadSouth = 65,
    PS4_CenterPad_DPadWest = 66,
    PS4_CenterPad_DPadEast = 67,
    PS4_LeftTrigger_Pull = 68,
    PS4_LeftTrigger_Click = 69,
    PS4_RightTrigger_Pull = 70,
    PS4_RightTrigger_Click = 71,
    PS4_LeftStick_Move = 72,
    PS4_LeftStick_Click = 73,
    PS4_LeftStick_DPadNorth = 74,
    PS4_LeftStick_DPadSouth = 75,
    PS4_LeftStick_DPadWest = 76,
    PS4_LeftStick_DPadEast = 77,
    PS4_RightStick_Move = 78,
    PS4_RightStick_Click = 79,
    PS4_RightStick_DPadNorth = 80,
    PS4_RightStick_DPadSouth = 81,
    PS4_RightStick_DPadWest = 82,
    PS4_RightStick_DPadEast = 83,
    PS4_DPad_North = 84,
    PS4_DPad_South = 85,
    PS4_DPad_West = 86,
    PS4_DPad_East = 87,
    PS4_Gyro_Move = 88,
    PS4_Gyro_Pitch = 89,
    PS4_Gyro_Yaw = 90,
    PS4_Gyro_Roll = 91,
    XBoxOne_A = 92,
    XBoxOne_B = 93,
    XBoxOne_X = 94,
    XBoxOne_Y = 95,
    XBoxOne_LeftBumper = 96,
    XBoxOne_RightBumper = 97,
    XBoxOne_Menu = 98,
    XBoxOne_View = 99,
    XBoxOne_LeftTrigger_Pull = 100,
    XBoxOne_LeftTrigger_Click = 101,
    XBoxOne_RightTrigger_Pull = 102,
    XBoxOne_RightTrigger_Click = 103,
    XBoxOne_LeftStick_Move = 104,
    XBoxOne_LeftStick_Click = 105,
    XBoxOne_LeftStick_DPadNorth = 106,
    XBoxOne_LeftStick_DPadSouth = 107,
    XBoxOne_LeftStick_DPadWest = 108,
    XBoxOne_LeftStick_DPadEast = 109,
    XBoxOne_RightStick_Move = 110,
    XBoxOne_RightStick_Click = 111,
    XBoxOne_RightStick_DPadNorth = 112,
    XBoxOne_RightStick_DPadSouth = 113,
    XBoxOne_RightStick_DPadWest = 114,
    XBoxOne_RightStick_DPadEast = 115,
    XBoxOne_DPad_North = 116,
    XBoxOne_DPad_South = 117,
    XBoxOne_DPad_West = 118,
    XBoxOne_DPad_East = 119,
    XBox360_A = 120,
    XBox360_B = 121,
    XBox360_X = 122,
    XBox360_Y = 123,
    XBox360_LeftBumper = 124,
    XBox360_RightBumper = 125,
    XBox360_Start = 126,
    XBox360_Back = 127,
    XBox360_LeftTrigger_Pull = 128,
    XBox360_LeftTrigger_Click = 129,
    XBox360_RightTrigger_Pull = 130,
    XBox360_RightTrigger_Click = 131,
    XBox360_LeftStick_Move = 132,
    XBox360_LeftStick_Click = 133,
    XBox360_LeftStick_DPadNorth = 134,
    XBox360_LeftStick_DPadSouth = 135,
    XBox360_LeftStick_DPadWest = 136,
    XBox360_LeftStick_DPadEast = 137,
    XBox360_RightStick_Move = 138,
    XBox360_RightStick_Click = 139,
    XBox360_RightStick_DPadNorth = 140,
    XBox360_RightStick_DPadSouth = 141,
    XBox360_RightStick_DPadWest = 142,
    XBox360_RightStick_DPadEast = 143,
    XBox360_DPad_North = 144,
    XBox360_DPad_South = 145,
    XBox360_DPad_West = 146,
    XBox360_DPad_East = 147,
    SteamV2_A = 148,
    SteamV2_B = 149,
    SteamV2_X = 150,
    SteamV2_Y = 151,
    SteamV2_LeftBumper = 152,
    SteamV2_RightBumper = 153,
    SteamV2_LeftGrip = 154,
    SteamV2_RightGrip = 155,
    SteamV2_Start = 156,
    SteamV2_Back = 157,
    SteamV2_LeftPad_Touch = 158,
    SteamV2_LeftPad_Swipe = 159,
    SteamV2_LeftPad_Click = 160,
    SteamV2_LeftPad_DPadNorth = 161,
    SteamV2_LeftPad_DPadSouth = 162,
    SteamV2_LeftPad_DPadWest = 163,
    SteamV2_LeftPad_DPadEast = 164,
    SteamV2_RightPad_Touch = 165,
    SteamV2_RightPad_Swipe = 166,
    SteamV2_RightPad_Click = 167,
    SteamV2_RightPad_DPadNorth = 168,
    SteamV2_RightPad_DPadSouth = 169,
    SteamV2_RightPad_DPadWest = 170,
    SteamV2_RightPad_DPadEast = 171,
    SteamV2_LeftTrigger_Pull = 172,
    SteamV2_LeftTrigger_Click = 173,
    SteamV2_RightTrigger_Pull = 174,
    SteamV2_RightTrigger_Click = 175,
    SteamV2_LeftStick_Move = 176,
    SteamV2_LeftStick_Click = 177,
    SteamV2_LeftStick_DPadNorth = 178,
    SteamV2_LeftStick_DPadSouth = 179,
    SteamV2_LeftStick_DPadWest = 180,
    SteamV2_LeftStick_DPadEast = 181,
    SteamV2_Gyro_Move = 182,
    SteamV2_Gyro_Pitch = 183,
    SteamV2_Gyro_Yaw = 184,
    SteamV2_Gyro_Roll = 185,
    Count = 186,
    EUWorksControllerActionOrigin_MAX = 187,
};

enum class EUWorksUserRestriction {
    Unknown = 0,
    AnyChat = 1,
    VoiceChat = 2,
    GroupChat = 3,
    Rating = 4,
    GameInvites = 5,
    Trading = 6,
    EUWorksUserRestriction_MAX = 7,
};

enum class EUWorksOverlaySpecific {
    SteamID = 0,
    Chat = 1,
    JoinTrade = 2,
    Stats = 3,
    Achievements = 4,
    FriendAdd = 5,
    FriendRemove = 6,
    FriendRequestAccept = 7,
    FriendRequestIgnore = 8,
    EUWorksOverlaySpecific_MAX = 9,
};

enum class EUWorksOverlayGeneric {
    Friends = 0,
    Community = 1,
    Players = 2,
    Settings = 3,
    OfficialGameGroup = 4,
    Stats = 5,
    Achievements = 6,
    EUWorksOverlayGeneric_MAX = 7,
};

enum class EUWorksPersonaState {
    Offline = 0,
    Online = 1,
    Busy = 2,
    Away = 3,
    Snooze = 4,
    LookingToTrade = 5,
    LookingToPlay = 6,
    Max = 7,
};

enum class EUWorksOverlayToStoreFlag {
    None = 0,
    AddToCart = 1,
    AddToCartAndShow = 2,
    EUWorksOverlayToStoreFlag_MAX = 3,
};

enum class EUWorksFriendRelationship {
    None = 0,
    Blocked = 1,
    RequestRecipient = 2,
    Friend = 3,
    RequestInitiator = 4,
    Ignored = 5,
    IgnoredFriend = 6,
    Max = 8,
};

enum class EUWorksFriendFlags {
    Blocked = 0,
    FriendshipRequested = 1,
    Immediate = 2,
    ClanMember = 3,
    OnGameServer = 4,
    HasPlayedWith = 5,
    FriendOfFriend = 6,
    RequestingFriendship = 7,
    RequestingInfo = 8,
    Ignored = 9,
    IgnoredFriend = 10,
    Suggested = 11,
    ChatMember = 12,
    All = 13,
    EUWorksFriendFlags_MAX = 14,
};

enum class EUWorksSteamItemFlags {
    NoTrade = 0,
    Removed = 8,
    Consumed = 9,
    EUWorksSteamItemFlags_MAX = 10,
};

enum class EUWorksLobbyType {
    Private = 0,
    FriendsOnly = 1,
    Public = 2,
    Invisible = 3,
    EUWorksLobbyType_MAX = 4,
};

enum class EUWorksLobbyDistanceFilter {
    Close = 0,
    Default = 1,
    Far = 2,
    Worldwide = 3,
    EUWorksLobbyDistanceFilter_MAX = 4,
};

enum class EUWorksLobbyComparison {
    EqualToOrLessThan = 0,
    LessThan = 1,
    Equal = 2,
    GreaterThan = 3,
    EqualToOrGreaterThan = 4,
    NotEqual = 5,
    EUWorksLobbyComparison_MAX = 6,
};

enum class EUWorksServerQueryType {
    Internet = 0,
    LAN = 1,
    Friends = 2,
    Favorites = 3,
    History = 4,
    Spectator = 5,
    EUWorksServerQueryType_MAX = 6,
};

enum class EUWorksAudioPlaybackStatus {
    Undefined = 0,
    Playing = 1,
    Paused = 2,
    Idle = 3,
    EUWorksAudioPlaybackStatus_MAX = 4,
};

enum class EUWorksP2PSend {
    Unreliable = 0,
    UnreliableNoDelay = 1,
    Reliable = 2,
    ReliableWithBuffering = 3,
    EUWorksP2PSend_MAX = 4,
};

enum class EUWorksRemoteStoragePlatform {
    Windows = 0,
    OSX = 1,
    PS3 = 2,
    Linux = 3,
    Reserved = 4,
    All = 5,
    EUWorksRemoteStoragePlatform_MAX = 6,
};

enum class EUWorksVRScreenshotType {
    None = 0,
    Mono = 1,
    Stereo = 2,
    MonoCubemap = 3,
    MonoPanorama = 4,
    StereoPanorama = 5,
    EUWorksVRScreenshotType_MAX = 6,
};

enum class EUWorksWorkshopFileType {
    Community = 0,
    Microtransaction = 1,
    Collection = 2,
    Art = 3,
    Video = 4,
    Screenshot = 5,
    Game = 6,
    Software = 7,
    Concept = 8,
    WebGuide = 9,
    IntegratedGuide = 10,
    Merch = 11,
    ControllerBinding = 12,
    SteamworksAccessInvite = 13,
    SteamVideo = 14,
    GameManagedItem = 15,
    Max = 16,
};

enum class EUWorksRemoteStoragePublishedFileVisibility {
    Public = 0,
    FriendsOnly = 1,
    Private = 2,
    EUWorksRemoteStoragePublishedFileVisibility_MAX = 3,
};

enum class EUWorksUserUGCListSortOrder {
    CreationOrderDesc = 0,
    CreationOrderAsc = 1,
    TitleAsc = 2,
    LastUpdatedDesc = 3,
    SubscriptionDateDesc = 4,
    VoteScoreDesc = 5,
    ForModeration = 6,
    EUWorksUserUGCListSortOrder_MAX = 7,
};

enum class EUWorksUserUGCList {
    Published = 0,
    VotedOn = 1,
    VotedUp = 2,
    VotedDown = 3,
    WillVoteLater = 4,
    Favorited = 5,
    Subscribed = 6,
    UsedOrPlayed = 7,
    Followed = 8,
    EUWorksUserUGCList_MAX = 9,
};

enum class EUWorksUGCQuery {
    RankedByVote = 0,
    RankedByPublicationDate = 1,
    AcceptedForGameRankedByAcceptanceDate = 2,
    RankedByTrend = 3,
    FavoritedByFriendsRankedByPublicationDate = 4,
    CreatedByFriendsRankedByPublicationDate = 5,
    RankedByNumTimesReported = 6,
    CreatedByFollowedUsersRankedByPublicationDate = 7,
    NotYetRated = 8,
    RankedByTotalVotesAsc = 9,
    RankedByVotesUp = 10,
    RankedByTextSearch = 11,
    RankedByTotalUniqueSubscriptions = 12,
    RankedByPlaytimeTrend = 13,
    RankedByTotalPlaytime = 14,
    RankedByAveragePlaytimeTrend = 15,
    RankedByLifetimeAveragePlaytime = 16,
    RankedByPlaytimeSessionsTrend = 17,
    RankedByLifetimePlaytimeSessions = 18,
    EUWorksUGCQuery_MAX = 19,
};

enum class EUWorksUGCMatchingUGCType {
    Items = 0,
    Items_Mtx = 1,
    Items_ReadyToUse = 2,
    Collections = 3,
    Artwork = 4,
    Videos = 5,
    Screenshots = 6,
    AllGuides = 7,
    WebGuides = 8,
    IntegratedGuides = 9,
    UsableInGame = 10,
    ControllerBindings = 11,
    GameManagedItems = 12,
    All = 254,
    EUWorksUGCMatchingUGCType_MAX = 255,
};

enum class EUWorksItemUpdateStatus {
    Invalid = 0,
    PreparingConfig = 1,
    PreparingContent = 2,
    UploadingContent = 3,
    UploadingPreviewFile = 4,
    CommittingChanges = 5,
    EUWorksItemUpdateStatus_MAX = 6,
};

enum class EUWorksItemStatistic {
    NumSubscriptions = 0,
    NumFavorites = 1,
    NumFollowers = 2,
    NumUniqueSubscriptions = 3,
    NumUniqueFavorites = 4,
    NumUniqueFollowers = 5,
    NumUniqueWebsiteViews = 6,
    ReportScore = 7,
    NumSecondsPlayed = 8,
    NumPlaytimeSessions = 9,
    NumComments = 10,
    EUWorksItemStatistic_MAX = 11,
};

enum class EUWorksItemState {
    None = 0,
    Subscribed = 1,
    LegacyItem = 2,
    Installed = 3,
    NeedsUpdate = 4,
    Downloading = 5,
    DownloadPending = 6,
    EUWorksItemState_MAX = 7,
};

enum class EUWorksItemPreviewType {
    Image = 0,
    YouTubeVideo = 1,
    Sketchfab = 2,
    EnvironmentMap_HorizontalCross = 3,
    EnvironmentMap_LatLong = 4,
    ReservedMax = 254,
    EUWorksItemPreviewType_MAX = 255,
};

enum class EUWorksVoiceResult {
    OK = 0,
    NotInitialized = 1,
    NotRecording = 2,
    NoData = 3,
    BufferTooSmall = 4,
    DataCorrupted = 5,
    Restricted = 6,
    UnsupportedCodec = 7,
    ReceiverOutOfDate = 8,
    ReceiverDidNotAnswer = 9,
    EUWorksVoiceResult_MAX = 10,
};

enum class EUWorksLeaderboardUploadScoreMethod {
    None = 0,
    KeepBest = 1,
    ForceUpdate = 2,
    EUWorksLeaderboardUploadScoreMethod_MAX = 3,
};

enum class EUWorksLeaderboardSortMethod {
    None = 0,
    Ascending = 1,
    Descending = 2,
    EUWorksLeaderboardSortMethod_MAX = 3,
};

enum class EUWorksLeaderboardDisplayType {
    None = 0,
    Numeric = 1,
    TimeSeconds = 2,
    TimeMilliSeconds = 3,
    EUWorksLeaderboardDisplayType_MAX = 4,
};

enum class EUWorksLeaderboardDataRequest {
    Global = 0,
    GlobalAroundUser = 1,
    Friends = 2,
    Users = 3,
    EUWorksLeaderboardDataRequest_MAX = 4,
};

enum class EUWorksNotificationPosition {
    TopLeft = 0,
    TopRight = 1,
    BottomLeft = 2,
    BottomRight = 3,
    EUWorksNotificationPosition_MAX = 4,
};

enum class EUWorksUniverse {
    Invalid = 0,
    Public = 1,
    Beta = 2,
    Internal = 3,
    Dev = 4,
    Max = 5,
};

enum class EUWorksGamepadTextInputMode {
    Normal = 0,
    Password = 1,
    EUWorksGamepadTextInputMode_MAX = 2,
};

enum class EUWorksGamepadTextInputLineMode {
    SingleLine = 0,
    MultipleLines = 1,
    EUWorksGamepadTextInputLineMode_MAX = 2,
};

enum class EUWorksCheckFileSignature {
    InvalidSignature = 0,
    ValidSignature = 1,
    FileNotFound = 2,
    NoSignaturesFoundForThisApp = 3,
    NoSignaturesFoundForThisFile = 4,
    EUWorksCheckFileSignature_MAX = 5,
};

enum class EUWorksUserHasLicenseForAppResult {
    HasLicense = 0,
    DoesNotHaveLicense = 1,
    NoAuth = 2,
    EUWorksUserHasLicenseForAppResult_MAX = 3,
};

enum class EUWorksBeginAuthSessionResult {
    OK = 0,
    InvalidTicket = 1,
    DuplicateRequest = 2,
    InvalidVersion = 3,
    GameMismatch = 4,
    ExpiredTicket = 5,
    EUWorksBeginAuthSessionResult_MAX = 6,
};

enum class EUWorksAccountType {
    Invalid = 0,
    Individual = 1,
    Multiseat = 2,
    GameServer = 3,
    AnonGameServer = 4,
    Pending = 5,
    ContentServer = 6,
    Clan = 7,
    Chat = 8,
    ConsoleUser = 9,
    AnonUser = 10,
    Max = 11,
};

