enum class EUWorksUserSession {
    None = 0,
    Client = 1,
    Web = 2,
    EUWorksUserSession_MAX = 3,
};

enum class EUWorksReportType {
    None = 0,
    GameSales = 1,
    SteamStore = 2,
    Settlement = 3,
    EUWorksReportType_MAX = 4,
};

enum class FUWorksHTTPResponse {
    Unknown = 0,
    Continue = 1,
    SwitchProtocol = 2,
    Ok = 3,
    Created = 4,
    Accepted = 5,
    Partial = 6,
    NoContent = 7,
    ResetContent = 8,
    PartialContent = 9,
    Ambiguous = 10,
    Moved = 11,
    Redirect = 12,
    RedirectMethod = 13,
    NotModified = 14,
    UseProxy = 15,
    RedirectKeepVerb = 16,
    BadRequest = 17,
    Denied = 18,
    PaymentReq = 19,
    Forbidden = 20,
    NotFound = 21,
    BadMethod = 22,
    NoneAcceptable = 23,
    ProxyAuthReq = 24,
    RequestTimeout = 25,
    Conflict = 26,
    Gone = 27,
    LengthRequired = 28,
    PrecondFailed = 29,
    RequestTooLarge = 30,
    UriTooLong = 31,
    UnsupportedMedia = 32,
    TooManyRequests = 33,
    RetryWith = 34,
    ServerError = 35,
    NotSupported = 36,
    BadGateway = 37,
    ServiceUnavail = 38,
    GatewayTimeout = 39,
    VersionNotSup = 40,
    FUWorksHTTPResponse_MAX = 41,
};

